language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - find . "(" -name "*.php" ")" -exec php --syntax-check --file "{}" ";"

notifications:
  email: false
