language: php
php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install

script:
  - vendor/bin/phpcs --config-set installed_paths $TRAVIS_BUILD_DIR/vendor/wp-coding-standards/wpcs
  - vendor/bin/phpcs --standard=LesterChan --extensions=php --ignore="*/vendor/*" -p -s .

notifications:
  email: false
